version: "3.8"
services:
  app:
    image: postgres-app
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Password123
      - DATABASE_URL=jdbc:postgresql://db:5432/demo
  db:
    container_name: db
    image: postgres
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=Password123
       - POSTGRES_DB=demo
    ports:
      - "5432:5432"












